all:
	@echo "This is the kerninstd top level makefile; doing nothing"

check:
	(cd immediates/sparc-sun-solaris2.6; make check)
	(cd sparc_reg/sparc-sun-solaris2.6; make check)
	(cd sparc_reg_set/sparc-sun-solaris2.6; make check)
	(cd sparc_instr/sparc-sun-solaris2.6; make check)
	(cd bitwise_dataflow_fn/sparc-sun-solaris2.6; make check)
